[llvm]
optimize = true
release-debuginfo = false
assertions = false
ninja = true
targets = "X86"
experimental-targets = ""
link-shared = false
[build]
build = "x86_64-unknown-linux-gnu"
host = ["x86_64-unknown-linux-gnu"]
target = ["x86_64-unknown-linux-gnu"]
cargo = "/var/tmp/portage/dev-lang/rust-1.45.0/work/rust-stage0/bin/cargo"
rustc = "/var/tmp/portage/dev-lang/rust-1.45.0/work/rust-stage0/bin/rustc"
docs = false
compiler-docs = false
submodules = false
python = "python3.7"
locked-deps = true
vendor = true
extended = true
tools = ["rustfmt","rls","analysis","src","cargo",]
verbose = 2
sanitizers = false
profiler = false
cargo-native-static = false
[install]
prefix = "/usr"
libdir = "lib"
docdir = "share/doc/rust-1.45.0"
mandir = "share/man"
[rust]
optimize = true
debug = false
debug-assertions = false
debuginfo-level-rustc = 0
backtrace = true
incremental = false
default-linker = "/etc/portage/compiler-wrapper/rust-clang"
parallel-compiler = false
channel = "stable"
rpath = false
verbose-tests = true
optimize-tests = true
codegen-tests = true
dist-src = false
remap-debuginfo = true
lld = true
backtrace-on-ice = true
jemalloc = false
[dist]
src-tarball = false
[target.x86_64-unknown-linux-gnu]
cc = "/etc/portage/compiler-wrapper/rust-clang"
cxx = "/etc/portage/compiler-wrapper/rust-clang++"
linker = "/etc/portage/compiler-wrapper/rust-clang"
ar = "llvm-ar"
